# -*- coding: utf-8 -*-
"""generation_script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jWDSBpZFAV2CahBtoDihtezFtHNNiupE
"""

!pip -q install transformers accelerate bitsandbytes sentencepiece huggingface_hub

from google.colab import drive
drive.mount("/content/drive")

from pathlib import Path
OUT_DIR = Path("/content/drive/MyDrive/llm_outputs")
OUT_DIR.mkdir(parents=True, exist_ok=True)

# ====== CELL: generation script (final pass, minimal + robust) ======
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from huggingface_hub import login

# Login once per runtime
login()

MODEL_ID = "meta-llama/Llama-3.2-3B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, use_fast=True, token=True)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

bnb = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
)

model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    device_map="auto",
    quantization_config=bnb,
    token=True,
)
model.eval()
print("Loaded:", MODEL_ID)

import json
from pathlib import Path
import re
from tqdm import tqdm
import random
import numpy as np

# -------------------------
# CONFIG
# -------------------------
IN_PATH = "/content/sampled_from_defan_500_NOMATH.jsonl"
OUT_PATH = "/content/drive/MyDrive/llm_outputs/sampled_from_defan_500_NOMATH_3B_temp0.9_topp1.0_maxtokens32.jsonl"

NUM_SAMPLES = 20
TEMPERATURE = 0.9
TOP_P = 1.0
MAX_NEW_TOKENS = 32

# Optional reproducibility (keeps runs repeatable; remove if you want different samples each rerun)
SEED = 441
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

# -------------------------
# PROMPT
# -------------------------
SYSTEM_MSG = "You are a question-answering assistant."

USER_INSTR = (
    "Answer the following question as briefly as possible.\n"
    "Return ONLY the correct final answer.\n"
    "For numeric answers, give an approximation.\n"
    "For dates, give an exact date.\n"
    "Do not add any additional notes, no commentary, no parentheticals, no lists, no fluff.\n"
    "Do not include any additional facts not explicitly asked for in the question.\n"
    "Keep your response length to no more than around 10-12 words.\n"
    "Do not mention any year other than the year in the question.\n"
    "If multiple equivalent phrasings of the same answer exist, you may choose any of them.\n"
    "You can be creative with your response style, as long as you make sure to give ONLY the correct final answer.\n"
)

def make_prompt(question: str) -> str:
    messages = [
        {"role": "system", "content": SYSTEM_MSG},
        {"role": "user", "content": USER_INSTR + f"Question: {question}"},
    ]
    return tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)

# -------------------------
# OUTPUT CLEANING (non-destructive; removes obvious junk)
# - joins lines
# - strips common openers
# - strips parentheticals (kills "(Note: ...)" behavior)
# - keeps at most 2 sentences to avoid ramble
# -------------------------
_sentence_end = re.compile(r"[.!?](?:\s|$)")

def clean_output(text: str, keep_sentences: int = 2, max_chars: int = 300) -> str:
    t = " ".join(ln.strip() for ln in str(text).strip().splitlines() if ln.strip())
    t = re.sub(r"^(Sure|Certainly|Of course|Here(?:'s| is)|The answer is)\b[:,]?\s*", "", t, flags=re.I).strip()
    t = re.sub(r"\([^)]*\)", "", t).strip()          # remove parenthetical notes
    t = re.sub(r"\s+", " ", t).strip()

    if t:
        ends = list(_sentence_end.finditer(t))
        if len(ends) >= keep_sentences:
            t = t[:ends[keep_sentences - 1].end()].strip()

    if len(t) > max_chars:
        t = t[:max_chars].rstrip()

    return t

# -------------------------
# GENERATION LOOP
# -------------------------
out = Path(OUT_PATH)
out.parent.mkdir(parents=True, exist_ok=True)
if out.exists():
    out.unlink()

with open(IN_PATH, "r", encoding="utf-8") as fin, open(OUT_PATH, "a", encoding="utf-8") as fout:
    for line in tqdm(fin, desc="Generating", ncols=100):
        line = line.strip()
        if not line:
            continue

        row = json.loads(line)
        question = row["question"]
        base_id = row.get("sample_id", row.get("id", ""))

        prompt = make_prompt(question)

        # truncation=True prevents pathological long questions from blowing context
        inputs = tokenizer(prompt, return_tensors="pt", truncation=True).to(model.device)
        input_len = inputs["input_ids"].shape[1]

        with torch.inference_mode():
            outputs = model.generate(
                **inputs,
                do_sample=True,
                temperature=TEMPERATURE,
                top_p=TOP_P,
                max_new_tokens=MAX_NEW_TOKENS,
                min_new_tokens=1,
                num_return_sequences=NUM_SAMPLES,
                pad_token_id=tokenizer.eos_token_id,
                eos_token_id=tokenizer.eos_token_id,
            )

        new_tokens = outputs[:, input_len:]
        decoded = tokenizer.batch_decode(new_tokens, skip_special_tokens=True)

        for j, text in enumerate(decoded):
            out_row = {
                "question": row["question"],
                "answer": row.get("answer", ""),
                "type": row.get("type", ""),
                "domain": row.get("domain", ""),
                "sample_id": f"{base_id}_{j}" if base_id != "" else f"{j}",
                "model_answer": clean_output(text, keep_sentences=2),
            }
            fout.write(json.dumps(out_row, ensure_ascii=False) + "\n")

        fout.flush()

print("Saved:", OUT_PATH)